# Generated by Django 6.0.4 on 2026-08-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('consumivel', 'Consumível'), ('servico', 'Serviço'), ('eletronico', 'Eletrônico'), ('movel', 'Móvel'), ('livro', 'Livro')], default='consumivel', max_length=20, verbose_name='Categoria'),
        ),
    ]
