# Generated by Django 6.0.4 on 2026-08-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição do evento'),
        ),
        migrations.AlterField(
            model_name='eventitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, help_text='Valor unitario pago na compra para este evento.', max_digits=10, verbose_name='Preço de compra'),
        ),
    ]
